use sequelize_passport;

INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Give an unexpected compliment.",200,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Let someone cut in front of you in line",300,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Let someone else take that primo parking spot.",400,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Buy a warm meal for someone in need.",400,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Write a gratitude list in the morning and again in the evening.",400,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Slow down so someone can merge in front of you in traffic.",400,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Help someone struggling to carry their grocery bags.",400,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Stop to assist someone who looks lost.",300,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Pick up a piece of litter on the street and throw it out.",300,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Pass along a compliment to a service worker’s boss.",300,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Take the time to write a great online review for a restaurant you love. ",400,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Give an extra tip and write an encouraging note along with it.",400,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Bring treats to your local fire station.",800,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Smile at someone who looks sad.",200,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Try to make sure every person in a group conversation feels included.",200,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Smile at five strangers.",200,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Return shopping carts for people at the grocery store.",200,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Pay the toll for the person behind you.",200,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Write a thank you note to your mail carrier.",400,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Keep an extra umbrella in your car to give to someone stuck in the rain. ",400,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Leave a note on someone’s car telling them how awesome they parked. ",400,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Have a LinkedIn account? Write a recommendation for coworker or connection. ",400,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Leave a gas gift card at a gas pump.",400,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Purchase extra dog or cat food and bring it to an animal shelter.",200,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Run an errand for a family member who is busy ",500,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Pay it Backward: buy coffee for the person behind you in line. ",500,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Send a positive text message to five different people right now. ",500,CURDATE(),CURDATE(),1);
INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE ("Put your phone away while in the company of others.",300,CURDATE(),CURDATE(),1);
-- INSERT INTO Tasks( TaskName, PointsEarned, createdAt, updatedAt,UserId) VALUE (" ",300,CURDATE(),CURDATE(),1);