use sequelize_passport;

insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Look in the mirror and find something about yourself that you love.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Call your loved one", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Compliment a friend",CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Pay for someone's coffee", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Offer to take a walk with someone", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Eat more veggies!", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Send someone flowers", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Dance with your partner or friend", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Go for a walk and pick up the litter you see.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Let someone go ahead of you in line.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Check in on an elderly neighbor.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Find five things in your home that you can donate.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Donate food to the food pantry.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Donate socks and supplies to the homeless shelter.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Call a friend you haven’t seen in a while to say hello.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Turn off the water while brushing your teeth.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Make a get well card for someone. Bonus points if you make a load and give them to a local hospital for the COVID unit.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Thank a healthcare worker.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Give high fives to a friend. (Even if its socially distanced)", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Donate coloring books and crayons to the children’s hospital.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Give a homeless person a pack of masks.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Instead of posting negativity online, spread some encouragement, hope, and love.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Give up your seat on the bus to another person.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Recommend someone your favorite book/movie that impacted your life.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Take the time to listen to someone, ask about their life and how they are the person they are today.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Be kind to yourself!", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Laugh with someone.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Tell someone a joke.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Share a favorite recipe or meal with someone.", CURDATE(), CURDATE(),100, 1);
insert into Tasks (TaskName, createdAt, updatedAt,pointsEarned, UserId) VALUES ("Learn your partner's love language.", CURDATE(), CURDATE(),100, 1);